### ISSUE TITLE
Questions on basic linear algebra exercises

### ISSUE THREAD

**Issue by zachahn** [changlinli/intro-to-technical-ai-safety-slides#5]
* What is "point-wise doubling"? From our research it sounded like "scaling by 2".
* We were a little confused by the question "distribute properties ... scalar addition".

I'll edit this issue as I find more, if I find anything! Just didn't want to lose these notes, please feel free to close.

**Comment by changlinli** [comment]
Yeah point-wise doubling is the same as scaling by 2.

Right yes the distribute issue. Let me fix that

**Comment by zachahn** [comment]
Thank you!
